site_name: My Docs
theme:
  name: material
  logo: assets/logo/JTCLogoWhite.png
  favicon: assets/logo/JTCLogoBlack.png

  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

plugins:
  - search

extra_css:
  - assets/css/style.css

nav:
  - Home: index.md
  - Lookups: lookups.md
  - Create Leads: create-lead.md
  - Get Leads: get-leads.md
